# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Htmltomd < Formula
  desc "Convert HTML files to markdown"
  homepage "https://github.com/david-mk-lawrence/htmltomd"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/david-mk-lawrence/htmltomd/releases/download/v0.2.0/htmltomd_0.2.0_Darwin_arm64.tar.gz"
      sha256 "56006f75bf3fd8cf7d93dd213acd22f99ca36e5c70091de6316ede7b479da394"

      def install
        bin.install "htmltomd"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/david-mk-lawrence/htmltomd/releases/download/v0.2.0/htmltomd_0.2.0_Darwin_x86_64.tar.gz"
      sha256 "167e2a474c7f43b09f8a6cc4ecd461d27ace30bf8f74a3e265e8fc824872a359"

      def install
        bin.install "htmltomd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/david-mk-lawrence/htmltomd/releases/download/v0.2.0/htmltomd_0.2.0_Linux_x86_64.tar.gz"
      sha256 "827b41468884ec5c4db87e4a2ef898b89c777be8d297c9376fa2b0133671a02c"

      def install
        bin.install "htmltomd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/david-mk-lawrence/htmltomd/releases/download/v0.2.0/htmltomd_0.2.0_Linux_arm64.tar.gz"
      sha256 "c90af416029db2e35b40a47b9ec785c0546ccf400a65f9095754dc726d831942"

      def install
        bin.install "htmltomd"
      end
    end
  end
end
