# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Htmltomd < Formula
  desc "Convert HTML files to markdown"
  homepage "https://github.com/david-mk-lawrence/html-to-md"
  version "0.1.12"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/david-mk-lawrence/html-to-md/releases/download/v0.1.12/html-to-md_0.1.12_Darwin_arm64.tar.gz"
      sha256 "f4e8edd597e81297ee70d92a6b3043b7dcf2f2b9fb8b65e3099c73669252752a"

      def install
        bin.install "html-to-md"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/david-mk-lawrence/html-to-md/releases/download/v0.1.12/html-to-md_0.1.12_Darwin_x86_64.tar.gz"
      sha256 "e85a2f0659132ae2c8584f61391be871a891b03284a2bddfc6b3f8ee60306cd2"

      def install
        bin.install "html-to-md"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/david-mk-lawrence/html-to-md/releases/download/v0.1.12/html-to-md_0.1.12_Linux_x86_64.tar.gz"
      sha256 "32792115cc5620358145c60b3fcdf5c7fc50623c14c52090808f0d266a3efffe"

      def install
        bin.install "html-to-md"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/david-mk-lawrence/html-to-md/releases/download/v0.1.12/html-to-md_0.1.12_Linux_arm64.tar.gz"
      sha256 "ff631b9e9a3330f4d1396b22b5b36d75c07a71b97cdbfc08b1340dc6461f8278"

      def install
        bin.install "html-to-md"
      end
    end
  end
end
